// models/order.js
class Order {
    constructor({ ORDER_ID, ORDER_NAME, PLACED_DATE, APPROVED_DATE, STATUS_ID, CURRENCY_UOM_ID, PRODUCT_STORE_ID, SALES_CHANNEL_ENUM_ID, GRAND_TOTAL, COMPLETED_DATE }) {
      this.ORDER_ID = ORDER_ID;
      this.ORDER_NAME = ORDER_NAME;
      this.PLACED_DATE = PLACED_DATE;
      this.APPROVED_DATE = APPROVED_DATE;
      this.STATUS_ID = STATUS_ID;
      this.CURRENCY_UOM_ID = CURRENCY_UOM_ID;
      this.PRODUCT_STORE_ID = PRODUCT_STORE_ID;
      this.SALES_CHANNEL_ENUM_ID = SALES_CHANNEL_ENUM_ID;
      this.GRAND_TOTAL = GRAND_TOTAL;
      this.COMPLETED_DATE = COMPLETED_DATE;
    }
  }
  
  module.exports = Order;
  